# Generated by Django 2.2.4 on 2019-08-08 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'categoría', 'verbose_name_plural': 'categorías'},
        ),
    ]
