# Generated by Django 2.2.4 on 2019-08-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_auto_20190808_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título del Curso')),
                ('codigo', models.SlugField(max_length=100, unique=True)),
                ('resumen', models.TextField(max_length=500, verbose_name='Descripción del Curso')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y hora')),
                ('imagen', models.ImageField(upload_to='cursos', verbose_name='Imagen')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicación')),
                ('tema', models.ManyToManyField(blank=True, null=True, to='core.Categoria', verbose_name='Temática')),
            ],
            options={
                'verbose_name': 'curso',
                'verbose_name_plural': 'cursos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
