# Generated by Django 2.2.4 on 2019-08-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Título del Curso'),
        ),
    ]
