# Generated by Django 2.2.4 on 2019-08-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_auto_20190819_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='codigo',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
