# Generated by Django 2.2.4 on 2019-08-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_auto_20190819_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='resumen',
            field=models.TextField(max_length=1000, verbose_name='Descripción del Curso'),
        ),
    ]
