# Generated by Django 2.2.4 on 2019-08-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_auto_20190820_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='resumen',
            field=models.TextField(max_length=1500, verbose_name='Descripción del Curso'),
        ),
    ]
