# Generated by Django 2.2.4 on 2019-08-18 23:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='fecha_agregado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha agregado'),
            preserve_default=False,
        ),
    ]
