# Generated by Django 2.2.4 on 2019-08-18 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlog', '0002_video_fecha_agregado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-fecha_agregado'], 'verbose_name': 'video', 'verbose_name_plural': 'videos'},
        ),
        migrations.AddField(
            model_name='video',
            name='video_titulo',
            field=models.CharField(default='Titulo 1', max_length=100, unique=True, verbose_name='Título'),
            preserve_default=False,
        ),
    ]
