# Generated by Django 2.2.4 on 2019-08-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(max_length=100, verbose_name='Título')),
                ('copete', models.TextField(max_length=50, verbose_name='Copete')),
                ('imagen', models.ImageField(upload_to='noticias', verbose_name='Imagen')),
                ('cuerpo', models.TextField(verbose_name='Cuerpo de la noticia')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de última edición')),
                ('categorias', models.ManyToManyField(blank=True, null=True, to='core.Categoria', verbose_name='Temas y/o categorías')),
            ],
        ),
    ]
