# Generated by Django 2.2.4 on 2019-08-08 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['-fecha_publicacion'], 'verbose_name': 'noticia', 'verbose_name_plural': 'noticias'},
        ),
    ]
