# Generated by Django 2.1.9 on 2019-08-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_auto_20190808_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Borrador'), (1, 'Publicado')], default=0),
        ),
    ]
