# Generated by Django 2.1.9 on 2019-08-09 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0005_auto_20190809_1010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='slug',
            new_name='codigo',
        ),
    ]
